[package]
name = "envfetch"
version = "1.0.0"
edition = "2021"
authors = ["ANKDDEV"]
description = "Lightweight cross-platform CLI tool for working with environment variables"
readme = "README.md"
license-file = "LICENSE"
homepage = "https://github.com/ankddev/envfetch"
repository = "https://github.com/ankddev/envfetch"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
similar-string = "1.4.3"
subprocess = "0.2.9"
dotenv-parser = "0.1.3"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"
assert_fs = "1.1.2"
