name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements to open issue
      description: By submitting this issue, you follow that you are followed all of this steps
      options:
        - label: Searched for similar issues
          required: true
        - label: Running on **latest** version
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - Latest from GitHub Actions
        - 2.0.0
        - 1.4.0
        - Other
      default: 0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Which platform are you use?
      options:
        - Android (with Termux)
        - Windows
        - Linux
        - macOS
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
