name: Build
on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose --locked
      - name: Upload artifacts for Windows
        if: ${{ matrix.os == 'windows-latest'}}
        uses: actions/upload-artifact@v4
        with:
          name: envfetch-debug-windows
          path: |
            target/debug/envfetch.exe
      - name: Upload artifacts for Linux
        if: ${{ matrix.os == 'ubuntu-latest'}}
        uses: actions/upload-artifact@v4
        with:
          name: envfetch-debug-linux
          path: |
            target/debug/envfetch
      - name: Upload artifacts for macOS
        if: ${{ matrix.os == 'macOS-latest'}}
        uses: actions/upload-artifact@v4
        with:
          name: envfetch-debug-macos
          path: |
            target/debug/envfetch
